version: '3.7'
services:  
  db:
    image: mysql:latest
    volumes:
      - db:/var/lib/mysql/
      - ./mysql-init:/docker-entrypoint-initdb.d:ro
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pass54321
      - MYSQL_DATABASE=budgetapp
      - MYSQL_USER=budgetapp
      - MYSQL_PASSWORD=pass12345
    ports:
      - 3306:3306
    networks:
      - dockernet
  phpmyadmin: 
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    #volumes:
    #  - ./:/var/www/html/
    ports:
      - 8899:80
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=pass54321
    networks:
      - dockernet
networks:
  dockernet:
    driver: bridge
volumes:
  db: